import product1 from "../../assets/images/bs-headphone.png";
import product2 from "../../assets/images/bs-homedecore.png";
import product3 from "../../assets/images/bs-makeup.png";
import product4 from "../../assets/images/bs-shoes.png";

export const bestSellingProducts = [
  {
    id: 101,
    title: "Electronics",
    brand: "Sony",
    image: product1,
    images: [product1],
    price: 2499,
    oldPrice: 4999,
    discount: 50,
    rating: 4.8,
    totalReviews: 456,
    sold: 2500,
    stock: true,
    description: "Premium electronics collection.",
    colors: ["#000000"],
    sizes: ["Standard"],
    fabric: "-",
    pattern: "-",
    occasion: "-",
    country: "India",
  },

  {
    id: 102,
    title: "Home Decor",
    brand: "Home Style",
    image: product2,
    images: [product2],
    price: 1799,
    oldPrice: 2999,
    discount: 40,
    rating: 4.7,
    totalReviews: 310,
    sold: 1200,
    stock: true,
    description: "Beautiful home decor products.",
    colors: ["#355E3B"],
    sizes: ["Standard"],
    fabric: "-",
    pattern: "-",
    occasion: "-",
    country: "India",
  },

  {
    id: 103,
    title: "Makeup",
    brand: "Beauty",
    image: product3,
    images: [product3],
    price: 1299,
    oldPrice: 1999,
    discount: 35,
    rating: 4.9,
    totalReviews: 620,
    sold: 3200,
    stock: true,
    description: "Professional makeup kit.",
    colors: ["#E91E63"],
    sizes: ["Standard"],
    fabric: "-",
    pattern: "-",
    occasion: "-",
    country: "India",
  },

  {
    id: 104,
    title: "Running Shoes",
    brand: "Nike",
    image: product4,
    images: [product4],
    price: 2199,
    oldPrice: 3499,
    discount: 37,
    rating: 4.8,
    totalReviews: 700,
    sold: 4200,
    stock: true,
    description: "Comfortable running shoes.",
    colors: ["#000000"],
    sizes: ["7", "8", "9", "10"],
    fabric: "-",
    pattern: "-",
    occasion: "Sports",
    country: "India",
  },
];